apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    # Esto no es mas que un arreglo de objetos[0: {"name":"nginx", "image":"nginx"}, 1: {"name":"python", "image":"python-apline"}]    
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
