apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  #Se indica que pod usara el replication controller 
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx-container
  replicas: 3

